# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tent_ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tent_ios
  pod 'Firebase/Analytics'

  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Functions'

  pod 'GoogleMaps'
  pod 'GooglePlaces'

  pod "Introspect"

end
